
service: aws-java-maven 

provider:
  name: aws
  runtime: java8

package:
  artifact: target/hello-dev.jar

functions:
  hello:
    handler: com.serverless.Handler
    events:
      - http:
          path: hello-world
          method: get
          cors: true